#!/bin/bash
#
# munin to graphite bridge initd script
#
# chkconfig: 3 50 50
# description: Munin to Graphite init.d script
. /etc/rc.d/init.d/functions

prog=graphite-munin
GMUNIN=/opt/graphite-munin
graphitehost=localhost
graphitemunin=${GMUNIN}/bin/graphite-munin
LOG=${GMUNIN}/log/graphite-munin.log
ERRLOG=${GMUNIN}/log/errors.log
CONFFILE=${GMUNIN}/etc/config.yml
pidfile=${GMUNIN}/var/graphite-munin.pid
#lockfile=${GMUNIN}/var/graphite-munin.lock
RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-10}

start() {
    echo -n $"Starting $prog: "
    cd ${GMUNIN}

    # See if it's already running. Look *only* at the pid file.
    if [ -f ${pidfile} ]; then
        failure "PID file exists for graphite-munin"
        RETVAL=1
    else
        # Run as process
        ${graphitemunin} 127.0.0.1 ${graphitehost} >> ${LOG} 2>> ${ERRLOG} &
        RETVAL=$?

        # Store PID
        echo $! > ${pidfile}

        # Success
        [ $RETVAL = 0 ] && success "graphite-munin started"
    fi

    echo
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p ${pidfile}
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${pidfile}
}

# See how we were called.
case "$1" in
  start)
    stop
    # Fix for puppet
    # in case of a dead process
    rm $pidfile > /dev/null 2>&1
    start

    ;;
  stop)
    stop
    ;;
  status)
    status -p ${pidfile} ${prog}
    RETVAL=$?
    ;;
  restart)
    stop
    start
    ;;
  condrestart)
    if [ -f ${pidfile} ] ; then
        stop
        start
    fi
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|condrestart|status}"
    exit 1
esac

exit $RETVAL
